# Generated by Django 4.2.27 on 2026-02-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='settings',
            new_name='user_settings',
        ),
    ]
