# Generated by Django 4.2.27 on 2026-02-05 10:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_archesinstance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesaurusid', models.UUIDField(default=uuid.uuid4)),
                ('label', models.CharField(default='', max_length=128)),
                ('labelid', models.UUIDField(blank=True, null=True)),
                ('load_on_demand', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesauri', to='api.archesinstance')),
            ],
            options={
                'unique_together': {('instance', 'thesaurusid')},
            },
        ),
    ]
