# Generated by Django 4.2.27 on 2026-02-05 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_thesaurus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptid', models.UUIDField(default=uuid.uuid4)),
                ('thesaurus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='api.thesaurus')),
            ],
            options={
                'unique_together': {('thesaurus', 'conceptid')},
            },
        ),
        migrations.CreateModel(
            name='ConceptProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.SlugField(max_length=128)),
                ('value', models.TextField(default='')),
                ('type', models.SlugField(default='literal', max_length=64)),
                ('lang', models.SlugField(default='en', max_length=64)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.concept')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptPredicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.SlugField(max_length=128)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicates_rev', to='api.concept')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicates', to='api.concept')),
                ('thesaurus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.thesaurus')),
            ],
        ),
    ]
