# Generated by Django 4.2.27 on 2026-02-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rdf_shenanigans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptpredicate',
            name='thesaurus',
        ),
    ]
