# Generated by Django 4.2.27 on 2026-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_conceptpredicate_thesaurus'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphmodel',
            name='cached_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
